"""Pure snapshot-domain contracts."""

from app.modules.snapshots.account_projection import (
    AccountSnapshotProjectionInput,
    AccountSnapshotProjectionStateError,
    CashBalanceEvidence,
    ConsumedExchangeRate,
    CurrencyAmount,
    ExpectedAccountSnapshotItem,
    ExpectedAccountSnapshotValuation,
    LiabilityBalanceEvidence,
    SelectedExchangeRateEvidence,
    SelectedPriceEvidence,
    SnapshotHoldingEvidence,
    build_account_snapshot_projection,
)
from app.modules.snapshots.persistence_projection import (
    AccountSnapshotPersistenceAudit,
    AccountSnapshotPersistenceMetadata,
    AccountSnapshotPersistenceProjectionError,
    CanonicalJsonObject,
    ExpectedAccountSnapshotItemRow,
    ExpectedAccountSnapshotPersistence,
    ExpectedAccountSnapshotRow,
    build_account_snapshot_persistence_projection,
)
from app.modules.snapshots.writer import (
    AccountSnapshotWriteConflictError,
    AccountSnapshotWriteDisposition,
    AccountSnapshotWriter,
    AccountSnapshotWriteResult,
    AccountSnapshotWriteStateError,
    WriteAccountSnapshotCommand,
)

__all__ = [
    "AccountSnapshotPersistenceAudit",
    "AccountSnapshotPersistenceMetadata",
    "AccountSnapshotPersistenceProjectionError",
    "AccountSnapshotProjectionInput",
    "AccountSnapshotProjectionStateError",
    "AccountSnapshotWriteConflictError",
    "AccountSnapshotWriteDisposition",
    "AccountSnapshotWriteResult",
    "AccountSnapshotWriteStateError",
    "AccountSnapshotWriter",
    "CanonicalJsonObject",
    "CashBalanceEvidence",
    "ConsumedExchangeRate",
    "CurrencyAmount",
    "ExpectedAccountSnapshotItem",
    "ExpectedAccountSnapshotItemRow",
    "ExpectedAccountSnapshotPersistence",
    "ExpectedAccountSnapshotRow",
    "ExpectedAccountSnapshotValuation",
    "LiabilityBalanceEvidence",
    "SelectedExchangeRateEvidence",
    "SelectedPriceEvidence",
    "SnapshotHoldingEvidence",
    "WriteAccountSnapshotCommand",
    "build_account_snapshot_persistence_projection",
    "build_account_snapshot_projection",
]
